spring:
  application:
    name: prreviewapp
  datasource:
    url: jdbc:mysql://localhost:3306/prreviewdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
logging:
  level:
    root: INFO
app:
  source: git-config-loaded