spring:
  application:
    name: prreviewapp

  datasource:
    url: jdbc:mysql://localhost:3306/prreview
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spring.cloud.vault.kv.prreviewapp.db.username}
    password: ${spring.cloud.vault.kv.prreviewapp.db.password}

  
logging:
  level:
    root: INFO

app:
  source: git-config-loaded
