spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prreviewdb
    username: root
    password: roor	
    #password: ${vault.db.password}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO

app:
  source: git-config-loaded
